[package]
name = "tcp_demo"
version = "0.1.0"
authors = ["w5pand <w5pand@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
